// benchmarks/deep-tree/vue/src/components/TreeNode.vue
<template>
  <div v-if="node.children.length === 0" class="leaf">
    {{ node.leafId }} v{{ leaf.version }} val:{{ leaf.value }}
  </div>
  <div v-else class="node">
    <div class="node-label">{{ node.id }}</div>
    <TreeNode
      v-for="child in node.children"
      :key="child.id"
      :node="child"
      :leaf-values="leafValues"
    />
  </div>
</template>

<script setup>
import { computed } from "vue"

const props = defineProps({
  node: {
    type: Object,
    required: true,
  },
  leafValues: {
    type: Object,
    required: true,
  },
})

const leaf = computed(() => {
  if (!props.node.leafId) {
    return { value: "-", version: "-" }
  }
  return props.leafValues[props.node.leafId]
})
</script>

// benchmarks/deep-tree/solid/src/components/TreeNode.jsx
import { createMemo } from "solid-js"

const LeafNode = (props) => {
  const snapshot = createMemo(() => props.leafValues[props.leafId])

  return (
    <div class="leaf">
      {props.leafId} v{snapshot().version} val:{snapshot().value}
    </div>
  )
}

export const TreeNode = (props) => {
  if (props.node.children.length === 0) {
    return <LeafNode leafId={props.node.leafId} leafValues={props.leafValues} />
  }

  return (
    <div class="node">
      <div class="node-label">{props.node.id}</div>
      {props.node.children.map((child) => (
        <TreeNode node={child} leafValues={props.leafValues} />
      ))}
    </div>
  )
}
