// benchmarks/deep-tree/react/src/App.jsx
import { useEffect, useMemo, useState } from "react"

import {
  applyCommitSample,
  applyFpsSample,
  createInitialMetrics,
  createInitialLeafValues,
  createTreeModel,
  UPDATE_INTERVAL,
  updateLeafValuesMutative,
} from "@benchmarks/deep-tree-shared"

import { Metrics } from "./components/Metrics"
import { TreeNode } from "./components/TreeNode"

const ONE_SECOND = 1000

const model = createTreeModel()

const createLeafStore = (initialLeafValues) => {
  const values = { ...initialLeafValues }
  const listenersByLeaf = new Map()

  const get = (leafId) => values[leafId]

  const subscribe = (leafId, listener) => {
    if (!listenersByLeaf.has(leafId)) {
      listenersByLeaf.set(leafId, new Set())
    }

    const leafListeners = listenersByLeaf.get(leafId)
    leafListeners.add(listener)

    return () => {
      leafListeners.delete(listener)
      if (leafListeners.size === 0) {
        listenersByLeaf.delete(leafId)
      }
    }
  }

  const updateRandomLeaf = () => {
    const updatedLeafId = updateLeafValuesMutative(values, model.leafIds)
    const leafListeners = listenersByLeaf.get(updatedLeafId)
    if (leafListeners) {
      leafListeners.forEach((listener) => listener())
    }
  }

  return {
    get,
    subscribe,
    updateRandomLeaf,
  }
}

export const App = () => {
  const [metrics, setMetrics] = useState(createInitialMetrics)
  const leafStore = useMemo(
    () => createLeafStore(createInitialLeafValues(model.leafIds)),
    [],
  )

  useEffect(() => {
    let rafId = 0
    let frameCount = 0
    let lastTime = performance.now()

    const countFPS = () => {
      frameCount += 1
      const now = performance.now()

      if (now >= lastTime + ONE_SECOND) {
        const fps = Math.round((frameCount * ONE_SECOND) / (now - lastTime))
        setMetrics((prev) => applyFpsSample(prev, fps))
        frameCount = 0
        lastTime = now
      }

      rafId = requestAnimationFrame(countFPS)
    }

    rafId = requestAnimationFrame(countFPS)

    return () => cancelAnimationFrame(rafId)
  }, [])

  useEffect(() => {
    const intervalId = setInterval(() => {
      const start = performance.now()

      leafStore.updateRandomLeaf()
      setMetrics((prev) => ({ ...prev, updateCount: prev.updateCount + 1 }))

      requestAnimationFrame(() => {
        setMetrics((prev) => applyCommitSample(prev, performance.now() - start))
      })
    }, UPDATE_INTERVAL)

    return () => clearInterval(intervalId)
  }, [leafStore])

  return (
    <div className="app">
      <div className="header">
        <div className="title">Deep Tree Sparse Updates: React</div>
        <Metrics
          metrics={metrics}
          nodes={model.totalNodes}
          leaves={model.totalLeaves}
        />
      </div>

      <div className="tree-container">
        <TreeNode node={model.root} leafStore={leafStore} />
      </div>
    </div>
  )
}

// benchmarks/deep-tree/svelte/src/App.svelte
<script>
  import { onDestroy } from "svelte"
  import { writable } from "svelte/store"

  import {
    applyCommitSample,
    applyFpsSample,
    createInitialMetrics,
    createInitialLeafValues,
    createTreeModel,
    UPDATE_INTERVAL,
    updateLeafValuesMutative,
  } from "@benchmarks/deep-tree-shared"

  import MetricsPanel from "./components/MetricsPanel.svelte"
  import TreeNode from "./components/TreeNode.svelte"

  const ONE_SECOND = 1000

  const model = createTreeModel()
  const initialLeafValues = createInitialLeafValues(model.leafIds)
  const leafValues = { ...initialLeafValues }
  const leafStores = new Map(
    Object.entries(initialLeafValues).map(([leafId, value]) => [
      leafId,
      writable(value),
    ]),
  )

  let metrics = createInitialMetrics()

  let frameCount = 0
  let lastTime = performance.now()
  let rafId

  const countFPS = () => {
    frameCount += 1
    const now = performance.now()

    if (now >= lastTime + ONE_SECOND) {
      const fps = Math.round((frameCount * ONE_SECOND) / (now - lastTime))
      metrics = applyFpsSample(metrics, fps)
      frameCount = 0
      lastTime = now
    }

    rafId = requestAnimationFrame(countFPS)
  }

  rafId = requestAnimationFrame(countFPS)

  const intervalId = setInterval(() => {
    const start = performance.now()

    const leafId = updateLeafValuesMutative(leafValues, model.leafIds)
    leafStores.get(leafId).set(leafValues[leafId])
    metrics = {
      ...metrics,
      updateCount: metrics.updateCount + 1,
    }

    requestAnimationFrame(() => {
      metrics = applyCommitSample(metrics, performance.now() - start)
    })
  }, UPDATE_INTERVAL)

  onDestroy(() => {
    cancelAnimationFrame(rafId)
    clearInterval(intervalId)
  })
</script>

<div class="app">
  <div class="header">
    <div class="title">Deep Tree Sparse Updates: Svelte</div>
    <MetricsPanel {metrics} nodes={model.totalNodes} leaves={model.totalLeaves} />
  </div>

  <div class="tree-container">
    <TreeNode node={model.root} {leafStores} />
  </div>
</div>
