// benchmarks/deep-tree/solid/src/components/TreeNode.jsx
import { createMemo } from "solid-js"

const LeafNode = (props) => {
  const snapshot = createMemo(() => props.leafValues[props.leafId])

  return (
    <div class="leaf">
      {props.leafId} v{snapshot().version} val:{snapshot().value}
    </div>
  )
}

export const TreeNode = (props) => {
  if (props.node.children.length === 0) {
    return <LeafNode leafId={props.node.leafId} leafValues={props.leafValues} />
  }

  return (
    <div class="node">
      <div class="node-label">{props.node.id}</div>
      {props.node.children.map((child) => (
        <TreeNode node={child} leafValues={props.leafValues} />
      ))}
    </div>
  )
}

// benchmarks/deep-tree/react/src/components/TreeNode.jsx
import { memo, useSyncExternalStore } from "react"

const LeafNode = memo(({ leafId, leafStore }) => {
  const snapshot = useSyncExternalStore(
    (onStoreChange) => leafStore.subscribe(leafId, onStoreChange),
    () => leafStore.get(leafId),
  )

  return (
    <div className="leaf">
      {leafId} v{snapshot.version} val:{snapshot.value}
    </div>
  )
})

LeafNode.displayName = "LeafNode"

export const TreeNode = memo(({ node, leafStore }) => {
  if (node.children.length === 0) {
    return <LeafNode leafId={node.leafId} leafStore={leafStore} />
  }

  return (
    <div className="node">
      <div className="node-label">{node.id}</div>
      {node.children.map((child) => (
        <TreeNode key={child.id} node={child} leafStore={leafStore} />
      ))}
    </div>
  )
})

TreeNode.displayName = "TreeNode"
