// benchmarks/deep-tree/svelte/src/components/TreeNode.svelte
<script>
  import LeafNode from "./LeafNode.svelte"

  export let node
  export let leafStores
</script>

{#if node.children.length === 0}
  <LeafNode leafId={node.leafId} leafStore={leafStores.get(node.leafId)} />
{:else}
  <div class="node">
    <div class="node-label">{node.id}</div>
    {#each node.children as child (child.id)}
      <svelte:self node={child} {leafStores} />
    {/each}
  </div>
{/if}

// benchmarks/deep-tree/react/src/components/TreeNode.jsx
import { memo, useSyncExternalStore } from "react"

const LeafNode = memo(({ leafId, leafStore }) => {
  const snapshot = useSyncExternalStore(
    (onStoreChange) => leafStore.subscribe(leafId, onStoreChange),
    () => leafStore.get(leafId),
  )

  return (
    <div className="leaf">
      {leafId} v{snapshot.version} val:{snapshot.value}
    </div>
  )
})

LeafNode.displayName = "LeafNode"

export const TreeNode = memo(({ node, leafStore }) => {
  if (node.children.length === 0) {
    return <LeafNode leafId={node.leafId} leafStore={leafStore} />
  }

  return (
    <div className="node">
      <div className="node-label">{node.id}</div>
      {node.children.map((child) => (
        <TreeNode key={child.id} node={child} leafStore={leafStore} />
      ))}
    </div>
  )
})

TreeNode.displayName = "TreeNode"
