// benchmarks/dashboard/svelte-store/src/components/DataTable.svelte
<script>
  import TableRow from "./TableRow.svelte"

  export let rows
  export let onSort
  export let onRowClick
</script>

<div class="table-container">
  <table>
    <thead>
      <tr>
        <th on:click={() => onSort("id")}>ID</th>
        <th>Name</th>
        <th on:click={() => onSort("value")}>Value</th>
        <th>Status</th>
        <th on:click={() => onSort("progress")}>Progress</th>
      </tr>
    </thead>
    <tbody>
      {#each rows as row (row.id)}
        <TableRow {row} onClick={onRowClick} />
      {/each}
    </tbody>
  </table>
</div>

// benchmarks/dashboard/solid-store-memo/src/components/DataTable.jsx
import { For } from "solid-js"

import { TableRow } from "./TableRow"

export const DataTable = (props) => {
  return (
    <div class="table-container">
      <table>
        <thead>
          <tr>
            <th onClick={() => props.onSort("id")}>ID</th>
            <th>Name</th>
            <th onClick={() => props.onSort("value")}>Value</th>
            <th>Status</th>
            <th onClick={() => props.onSort("progress")}>Progress</th>
          </tr>
        </thead>
        <tbody>
          <For each={props.rows}>
            {(row) => <TableRow row={row} onClick={props.onRowClick} />}
          </For>
        </tbody>
      </table>
    </div>
  )
}
