// benchmarks/dashboard/vue-pinia/src/components/Chart.vue
<script setup>
defineProps({
  chartData: {
    type: Object,
    required: true,
  },
})
</script>

<template>
  <div class="chart">
    <h3>{{ chartData.title }}</h3>
    <div class="chart-bars">
      <div
        v-for="(value, i) in chartData.values"
        :key="i"
        class="bar"
        :style="{
          height: `${(value / chartData.max) * 100}px`,
          backgroundColor: `hsl(${(value / chartData.max) * 120}, 70%, 50%)`,
        }"
      />
    </div>
    <div class="chart-info">Avg: {{ chartData.avg }}</div>
  </div>
</template>

// benchmarks/dashboard/react/src/components/Chart.jsx
export const Chart = ({ chartData }) => {
  const { title, values, max, avg } = chartData

  return (
    <div className="chart">
      <h3>{title}</h3>
      <div className="chart-bars">
        {values.map((value, i) => (
          <div
            key={i}
            className="bar"
            style={{
              height: `${(value / max) * 100}px`,
              backgroundColor: `hsl(${(value / max) * 120}, 70%, 50%)`,
            }}
          />
        ))}
      </div>
      <div className="chart-info">Avg: {avg}</div>
    </div>
  )
}
