// benchmarks/dashboard/svelte-store/src/components/DataTable.svelte
<script>
  import TableRow from "./TableRow.svelte"

  export let rows
  export let onSort
  export let onRowClick
</script>

<div class="table-container">
  <table>
    <thead>
      <tr>
        <th on:click={() => onSort("id")}>ID</th>
        <th>Name</th>
        <th on:click={() => onSort("value")}>Value</th>
        <th>Status</th>
        <th on:click={() => onSort("progress")}>Progress</th>
      </tr>
    </thead>
    <tbody>
      {#each rows as row (row.id)}
        <TableRow {row} onClick={onRowClick} />
      {/each}
    </tbody>
  </table>
</div>

// benchmarks/dashboard/react/src/components/DataTable.jsx
import { TableRow } from "./TableRow"

export const DataTable = ({ rows, onSort, onRowClick }) => {
  return (
    <div className="table-container">
      <table>
        <thead>
          <tr>
            <th onClick={() => onSort("id")}>ID</th>
            <th>Name</th>
            <th onClick={() => onSort("value")}>Value</th>
            <th>Status</th>
            <th onClick={() => onSort("progress")}>Progress</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <TableRow key={row.id} row={row} onClick={onRowClick} />
          ))}
        </tbody>
      </table>
    </div>
  )
}
