// benchmarks/dashboard/svelte-runes/src/components/TableRow.svelte
<svelte:options runes={true} />

<script>
  let { row, onClick } = $props()
</script>

<tr onclick={() => onClick(row.id)}>
  <td>{row.rowId}</td>
  <td>{row.name}</td>
  <td>{row.value}</td>
  <td>
    <span class={`status status-${row.status.toLowerCase()}`}>{row.status}</span>
  </td>
  <td>
    <div class="progress-bar">
      <div class="progress-fill" style={`width: ${row.progress}%`}></div>
      <span class="progress-text">{row.progress}%</span>
    </div>
  </td>
</tr>

// benchmarks/dashboard/react/src/components/TableRow.jsx
export const TableRow = ({ row, onClick }) => {
  return (
    <tr onClick={() => onClick(row.id)}>
      <td>{row.rowId}</td>
      <td>{row.name}</td>
      <td>{row.value}</td>
      <td>
        <span className={`status status-${row.status.toLowerCase()}`}>
          {row.status}
        </span>
      </td>
      <td>
        <div className="progress-bar">
          <div
            className="progress-fill"
            style={{ width: `${row.progress}%` }}
          />
          <span className="progress-text">{row.progress}%</span>
        </div>
      </td>
    </tr>
  )
}
